// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMnNh8v1TThZglP5x2EWnC-fdMq4m4sgQ',
    appId: '1:1060404560463:web:f37621334cd4cd8c09a03a',
    messagingSenderId: '1060404560463',
    projectId: 'pick-me-fafe2',
    authDomain: 'pick-me-fafe2.firebaseapp.com',
    storageBucket: 'pick-me-fafe2.firebasestorage.app',
    measurementId: 'G-YC46SRR0B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD95bi4gnTKCsFNl76fJcSVrWFQ-3tLOwc',
    appId: '1:1060404560463:android:cf076d5303f0fa8b09a03a',
    messagingSenderId: '1060404560463',
    projectId: 'pick-me-fafe2',
    storageBucket: 'pick-me-fafe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7bmApuiES601EgZ4LWSi2nXfJkLtyN0k',
    appId: '1:1060404560463:ios:52e521914774ddf309a03a',
    messagingSenderId: '1060404560463',
    projectId: 'pick-me-fafe2',
    storageBucket: 'pick-me-fafe2.firebasestorage.app',
    iosBundleId: 'com.pickme.pickmeride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7bmApuiES601EgZ4LWSi2nXfJkLtyN0k',
    appId: '1:1060404560463:ios:cebe3308c38f687609a03a',
    messagingSenderId: '1060404560463',
    projectId: 'pick-me-fafe2',
    storageBucket: 'pick-me-fafe2.firebasestorage.app',
    iosBundleId: 'com.pickme.pickme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMnNh8v1TThZglP5x2EWnC-fdMq4m4sgQ',
    appId: '1:1060404560463:web:203cabd443ee8eb709a03a',
    messagingSenderId: '1060404560463',
    projectId: 'pick-me-fafe2',
    authDomain: 'pick-me-fafe2.firebaseapp.com',
    storageBucket: 'pick-me-fafe2.firebasestorage.app',
    measurementId: 'G-WWVZCEZMS0',
  );

}