// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAErpykXQQ_I1uQxSkXuX4Fwy5ZVr09Wkc',
    appId: '1:836831611903:web:a2a238575ad7eb0f7af5ca',
    messagingSenderId: '836831611903',
    projectId: 'pick-me-46b4e',
    authDomain: 'pick-me-46b4e.firebaseapp.com',
    storageBucket: 'pick-me-46b4e.firebasestorage.app',
    measurementId: 'G-7G42F7HWC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5crvDMblFtfSBWuJ2A63dpuOw4GC1ZcM',
    appId: '1:836831611903:android:7f342987af72bcfd7af5ca',
    messagingSenderId: '836831611903',
    projectId: 'pick-me-46b4e',
    storageBucket: 'pick-me-46b4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnuyJziSXqcG07oojHjlUQ_XZeRHDvYLc',
    appId: '1:836831611903:ios:dac61bf8b5e6b63f7af5ca',
    messagingSenderId: '836831611903',
    projectId: 'pick-me-46b4e',
    storageBucket: 'pick-me-46b4e.firebasestorage.app',
    iosBundleId: 'com.pickme.pickme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnuyJziSXqcG07oojHjlUQ_XZeRHDvYLc',
    appId: '1:836831611903:ios:dac61bf8b5e6b63f7af5ca',
    messagingSenderId: '836831611903',
    projectId: 'pick-me-46b4e',
    storageBucket: 'pick-me-46b4e.firebasestorage.app',
    iosBundleId: 'com.pickme.pickme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAErpykXQQ_I1uQxSkXuX4Fwy5ZVr09Wkc',
    appId: '1:836831611903:web:fdabdaf7ea6ae5397af5ca',
    messagingSenderId: '836831611903',
    projectId: 'pick-me-46b4e',
    authDomain: 'pick-me-46b4e.firebaseapp.com',
    storageBucket: 'pick-me-46b4e.firebasestorage.app',
    measurementId: 'G-S6JTKDDG0N',
  );

}